### ISSUE TITLE
Looking for maintainer 

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/semantic-ui-sass#7]
I no longer use Semantic-UI therefore I don't keep up to date on it and it's causing this library to suffer. If anyone is willing to step up and take control of it, I'm more than willing to allow that.

**Comment by chrispaynter** [comment]
Hey @joshmanders, 

I have a long running web app and site that use the CSS for semantic ui, but need to move to sass in order to control which elements are imported.

Therefore, with a long term commitment to the framework, I'm currently feeling like taking over the repo would be a good option for me.

Seems pretty much that you've mapped the original sass files one for one. Based on what you've currently got committed, is it generally a case of porting the source repo's changes across as they become available? It seems that way based on my initial look through.

**Comment by joshmanders** [comment]
Yeah, the gulp command just clones down the ruby version of this lib, converts it, and does a bit of transformation to make a few customizations possible, then I make sure nothing broke and publish a release trying to match the same version as the version of Semantic-UI.

I can add you as a collab on the repo and npm module for publishing rights.

**Comment by joshmanders** [comment]
Thanks to @binkydog for stepping up.
